/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Owner;

import Class.Owner;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MUHAMMED BILAL
 */
public class ViewAll_Owner extends javax.swing.JFrame {

    /**
     * Creates new form ViewAll_Owner
     */
    int i=0;
    owner.DatabaseConnectivity objConnectivity;
    private Connection Connection;
    public ViewAll_Owner() {
        initComponents();
        objConnectivity=new owner.DatabaseConnectivity();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viewall = new javax.swing.JTable();
        back = new javax.swing.JButton();
        view = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        viewall.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail", "Phone No", "CNIC", "DOB", "Nationality"
            }
        ));
        viewall.setEnabled(false);
        jScrollPane2.setViewportView(viewall);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(60, 0, 930, 510);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Icon/icons8-back-arrow-48.png"))); // NOI18N
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(10, 20, 50, 57);

        view.setText("View");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jPanel1.add(view);
        view.setBounds(0, 220, 60, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PSL Background/green_background_3-wallpaper-1920x1080.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 990, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed

        if(i==0){
        try{
            Connection=objConnectivity.getConnection();
            Statement objStatement = Connection.createStatement();
            ResultSet objResultSet = objStatement.executeQuery("select * from ownerdb");
            ArrayList<Owner> objList = new ArrayList<Owner>();
            while(objResultSet.next()){
                Owner o=new Owner(objResultSet.getInt(1),objResultSet.getString(2),objResultSet.getString(3),objResultSet.getInt(4),objResultSet.getInt(5),objResultSet.getDate(6),objResultSet.getString(7));
                objList.add(o);

            }
            String[] columnsName = {"Owner_id", "Name", "Mail", "Cnic","PhoneNo","DOB","Nationality"};
            DefaultTableModel model = (DefaultTableModel) viewall.getModel();
            model.setColumnIdentifiers(columnsName);
            Object[] tableLines = new Object[7];
            for(int i=0;i<objList.size();i++){
                objList.get(i);
                tableLines[0]=objList.get(i).getId();
                tableLines[1]=objList.get(i).getName();
                tableLines[2]=objList.get(i).getMail();
                tableLines[3]=objList.get(i).getCnic();
                tableLines[4]=objList.get(i).getPhonenumber();
                tableLines[5]=objList.get(i).getDate();
                tableLines[6]=objList.get(i).getNationality();
                model.addRow(tableLines);
            }
        }catch (Exception e) {
            e.printStackTrace();
        }
        i++;
        }
        else{
            JOptionPane.showMessageDialog(this,"Stop Clicking on View button All data are Displayed! ");
        }
    }//GEN-LAST:event_viewActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Owner_Menu().setVisible(true);
            }
        });
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAll_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAll_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAll_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAll_Owner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAll_Owner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton view;
    private javax.swing.JTable viewall;
    // End of variables declaration//GEN-END:variables
}
